name: Test project
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get command
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run test
        run: npm test
        